DB_PATH = "./db"
USER_DB_PATH = f"{DB_PATH}/user.db"
TMP_PATH = "./tmp/"
COOKIE_PATH = "./cookie"
PDF_TEMPLATE_PATH = "Berichtsheft_template.pdf"
TODOLIST_TEMPLATE_PATH = "./todolist_template.json"
USER_PATH = f"{DB_PATH}/users"
# relative from user directory:
CONTENT_DB_PATH = f"content.db"
TODOLIST_PATH = f"todolist.json"
