#!/bin/env bash

# set environment variables
export FLASK_APP=rbwriter
export FLASK_ENV=production

if [ "$1" == "debug" ]; then
    echo "Running in debug mode!"
    export FLASK_ENV=development
    flask run --debug
    exit
else
  # hand over everything (cmd options) to flask
  flask "$@"
fi
